In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

In [2]:
path ="GlassdoorUSA.csv"
class DataFrame_Loader():
    data = path
    
    def __init__(self):
        
        print("Loadind DataFrame")
        
    def read_csv(self,data):
        self.df = pd.read_csv(data)
        
    def load_csv(self):
        return self.df

In [3]:
Data = DataFrame_Loader()

Loadind DataFrame

In [4]:
Data.read_csv(path)

In [5]:
df = Data.load_csv()

In [7]:
class DataFrame_Information():

    def __init__(self):
        
        print("Attribute Information object created")
        
    def Feature_information(self,data):
    
        data_info = pd.DataFrame(
                                columns=['No of observation',
                                        'No of Variables',
                                        'No of Numerical Variables',
                                        'No of Factor Variables',
                                        'No of Categorical Variables',
                                        'No of Logical Variables',
                                        'No of Date Variables',
                                        'No of zero variance variables'])


        data_info.loc[0,'No of observation'] = df.shape[0]
        data_info.loc[0,'No of Variables'] = df.shape[1]
        data_info.loc[0,'No of Numerical Variables'] = df._get_numeric_data().shape[1]
        data_info.loc[0,'No of Factor Variables'] = df.select_dtypes(include='category').shape[1]
        data_info.loc[0,'No of Logical Variables'] = df.select_dtypes(include='bool').shape[1]
        data_info.loc[0,'No of Categorical Variables'] = df.select_dtypes(include='object').shape[1]
        data_info.loc[0,'No of Date Variables'] = df.select_dtypes(include='datetime64').shape[1]
        data_info.loc[0,'No of zero variance variables'] = df.loc[:,df.apply(pd.Series.nunique)==1].shape[1]

        data_info =data_info.transpose()
        data_info.columns=['value']
        data_info['value'] = data_info['value'].astype(int)


        return data_info
        
    def Value_Counts_of_Data(self,data):
        categorical_columns = [x for x in data.dtypes.index if data.dtypes[x]=='object']
        for col in categorical_columns:
            print('\nFrequency of Categories for varible %s'%col)
            print(data[col].value_counts())
            
    def DataFrame_Aggregation(self,data):
        
        print("=" * 110)
        print("Aggregation of Table")
        print("=" * 110)
        table = pd.DataFrame(data.dtypes,columns=['dtypes'])
        table1 =pd.DataFrame(data.columns,columns=['Names'])
        table = table.reset_index()
        table= table.rename(columns={'index':'Name'})
        table['No of Missing'] = data.isnull().sum().values    
        table['No of Uniques'] = data.nunique().values
        table['Percent of Missing'] = ((data.isnull().sum().values)/ (data.shape[0])) *100
        table['First Observation'] = data.loc[0].values
        table['Second Observation'] = data.loc[1].values
        table['Third Observation'] = data.loc[2].values
        for name in table['Name'].value_counts().index:
            table.loc[table['Name'] == name, 'Entropy'] = round(stats.entropy(data[name].value_counts(normalize=True), base=2),2)
        return table
    
        print("=" * 110)
        
    def __IQR(self,x):
        return x.quantile(q=0.75) - x.quantile(q=0.25)

    def __Outlier_Count(self,x):
        upper_out = x.quantile(q=0.75) + 1.5 * self.__IQR(x)
        lower_out = x.quantile(q=0.25) - 1.5 * self.__IQR(x)
        return len(x[x > upper_out]) + len(x[x < lower_out])

        
    def Numeric_Count_Summary(self,df):
        df_num = df._get_numeric_data()
        data_info_num = pd.DataFrame()
        i=0
        for c in  df_num.columns:
            data_info_num.loc[c,'Negative values count']= df_num[df_num[c]<0].shape[0]
            data_info_num.loc[c,'Positive values count']= df_num[df_num[c]>0].shape[0]
            data_info_num.loc[c,'Zero count']= df_num[df_num[c]==0].shape[0]
            data_info_num.loc[c,'Unique count']= len(df_num[c].unique())
            data_info_num.loc[c,'Negative Infinity count']= df_num[df_num[c]== -np.inf].shape[0]
            data_info_num.loc[c,'Positive Infinity count']= df_num[df_num[c]== np.inf].shape[0]
            data_info_num.loc[c,'Missing Percentage']= df_num[df_num[c].isnull()].shape[0]/ df_num.shape[0]
            data_info_num.loc[c,'Count of outliers']= self.__Outlier_Count(df_num[c])
            i = i+1
        return data_info_num
    
    def Statistical_Summary(self,df):
    
        df_num = df._get_numeric_data()

        data_stat_num = pd.DataFrame()

        try:
            data_stat_num = pd.concat([df_num.describe().transpose(),
                                       pd.DataFrame(df_num.quantile(q=0.10)),
                                       pd.DataFrame(df_num.quantile(q=0.90)),
                                       pd.DataFrame(df_num.quantile(q=0.95))],axis=1)
            data_stat_num.columns = ['count','mean','std','min','25%','50%','75%','max','10%','90%','95%']
        except:
            pass

        return data_stat_num

In [8]:
Info = DataFrame_Information()

Attribute Information object created

In [9]:
Info.Feature_information(df)

                               value
No of observation               1000
No of Variables                   15
No of Numerical Variables          3
No of Factor Variables             0
No of Categorical Variables       12
No of Logical Variables            0
No of Date Variables               0
No of zero variance variables      0

In [10]:
Info.Value_Counts_of_Data(df)

Frequency of Categories for varible Job Title
Data Scientist                                                      295
Senior Data Scientist                                                70
Lead Data Scientist                                                  37
Principal Data Scientist                                             19
Sr. Data Scientist                                                   12
                                                                   ...
Senior Data Scientist - Experimentation for Globalization             1
Senior AI/ML Data Scientist with Extensive Industrial Experience      1
Data Scientist, Advertising                                           1
Senior Data Scientist - Personalization                               1
Data Scientist - Relocate to Washington D.C.                          1
Name: Job Title, Length: 437, dtype: int64

Frequency of Categories for varible Salary Estimate
$87K-$149K (Glassdoor Est.)     30
$200K-$250K(Employer Est.)      30
$71K-$110K (Glassdoor Est.)     30
$86K-$143K (Glassdoor Est.)     30
$125K-$156K (Glassdoor Est.)    30
$96K-$101K (Glassdoor Est.)     30
$113K-$190K (Glassdoor Est.)    30
$110K-$177K (Glassdoor Est.)    30
$94K-$114K (Glassdoor Est.)     30
$79K-$133K (Glassdoor Est.)     30
$100K-$150K (Glassdoor Est.)    30
$92K-$132K (Glassdoor Est.)     30
$94K-$116K (Glassdoor Est.)     30
$110K-$145K (Glassdoor Est.)    30
$89K-$128K (Glassdoor Est.)     30
$88K-$99K (Glassdoor Est.)      30
$129K-$148K (Glassdoor Est.)    30
$141K-$225K (Glassdoor Est.)    30
$50K-$100K (Glassdoor Est.)     30
$89K-$147K (Glassdoor Est.)     30
$117K-$150K (Glassdoor Est.)    30
$132K-$163K (Glassdoor Est.)    30
$70K-$123K (Glassdoor Est.)     30
$136K-$224K (Glassdoor Est.)    30
$141K-$170K (Glassdoor Est.)    30
$97K-$137K (Glassdoor Est.)     30
$111K-$153K (Glassdoor Est.)    30
$116K-$143K (Glassdoor Est.)    30
$212K-$332K (Glassdoor Est.)    30
$101K-$133K (Glassdoor Est.)    30
$127K-$139K (Glassdoor Est.)    30
$120K-$135K (Glassdoor Est.)    30
$58K-$99K (Glassdoor Est.)      20
$112K-$143K (Glassdoor Est.)    10
$93K-$148K (Glassdoor Est.)     10
Name: Salary Estimate, dtype: int64

Frequency of Categories for varible Job Description
Sartorius Stedim Data Analytics, a market leader in advanced analytics and provider of Umetrics Suite of Data Analytics Solutions, is on a strong growth path driving new innovative solutions in the field. It currently has an outstanding opportunity for a Data Scientist to drive customer applications, support the Sartorius sales teams and feedback customer needs into the development of new solutions. The incumbent for this key role will have a strong customer focus to help secure innovation and growth from both new and existing customers.\n\nWhat you can look forward to\nAssisting customers in solving business related problems using advanced data analysis and data driven technologies\nSupporting implementation of advanced analytics in industry\nAnalyzing large amounts of data and building data driven models\nInitiating, leading and driving customer projects\nTraining customers on the use of our software\nSupporting Sartorius sales (pre/post)\nSupporting marketing & development\nPerforming regular follow up with customers to track satisfaction, secure project momentum and discover additional opportunities\nCreating technical documents\nAttending and presenting at conferences, seminars and forums\nDeveloping & cultivating strong relationships with external and internal stakeholders\nBeing part of a team of data scientists\nSkills and experience\nMinimum a bachelor’s degree in a relevant field (engineering, life sciences, informatics, etc.), master’s degree preferred\nMinimum two years’ work experience within Biopharma or Pharma\nMinimum two years’ working knowledge of applied statistics such as MVDA, DOE, MSPC, PAT, QbD, Model Predictive Control (MPC), MMPC, AI/Machine learning\nBioprocess knowledge preferred\nFamiliarity with Umetrics Suite of Data Analytics Solutions preferred (MODDE, SIMCA, SIMCA-online, Control Advisor, Active Dashboard)\nWorking knowledge of prescriptive analytics a plus\nWorking knowledge of Python scripting preferred\nWorking knowledge of MATLAB, data historians & control strategy a plus\nTeaching, consulting and project management experience a plus\nExcellent communications skills, strong presentation skills a plus\nComfortable working independently\nComfortable working from home office, willingness to travel (~25%)\nStrong identification with Sartorius core values: sustainability, openness, enjoyment\nDriving our future growth requires talented people. Sartorius is a dynamic organization suited to people who want to showcase skills, be recognized for expertise and thrive in a vibrant and innovative environment.\n\nAll qualified applicants will receive consideration for employment without regard to race, color, religion, sex or national origin. We are also an equal opportunity employer of individuals with disabilities and protected veterans.\n\nPlease view equal employment opportunity posters provided by OFCCP here\n\nhttps://e-verify.uscis.gov/esp/media/resourcesContents/EverifyPosterEnglish.pdf\n\nhttps://e-verify.uscis.gov/esp/media/resourcesContents/EverifyPosterSpanish.pdf\n\nhttps://e-verify.uscis.gov/esp/media/resourcesContents/WebBPPOSTERRtoWEnglishversion.pdf\n\nhttps://e-verify.uscis.gov/esp/media/resourcesContents/WebBPPOSTERRtoWSpanishversion.pdf\n\nInterested? Driving our future growth requires talented people. Sartorius is a dynamic organisation suited to people who want to showcase skills, be recognised for expertise and thrive in a vibrant and innovative environment.\n\nTo find out more about Sartorius as an employer visit us on Sartorius Careers\n\nBecome part of our global team.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        3
Note: By applying to this position your application is automatically submitted to the following locations: New York, NY, USA; Mountain View, CA, USA; Seattle, WA, USA\n\nMinimum qualifications:\nMaster's degree in a quantitative discipline (e.g., Statistics, Bioinformatics, Economics) or equivalent practical experience.\n10 years of experience in data analysis or related field as a Statistician, Data Scientist, Computational Biologist, or bioinformatician.\n5 years of experience in people management or leadership.\nExperience with statistical software (e.g., R, Python, MATLAB, pandas) and database languages.\nPreferred qualifications:\nDoctorate's degree in a quantitative discipline (e.g., Statistics, Operations Research, Bioinformatics, Economics, Computational Biology, Computer Science, Mathematics, Physics, Electrical Engineering, Industrial Engineering).\n12 years of tech industry work experience as a statistician, bioinformatician, or data scientist. Experience in statistical data analysis, such as linear models, multivariate analysis, stochastic models, and sampling methods.\n8 years of leadership experience, including people management.\nApplied experience with machine learning on large datasets.\nExperience articulating business questions and using mathematical techniques to arrive at an answer using available data.\nAbility to select the right statistical tools given a data analysis problem.\nAbout the job\n\n\nAt Google, data drives all of our decision-making. Data Scientists work all across the organization to help shape Google's business and technical strategies by processing, analyzing and interpreting huge data sets. Using analytical excellence and statistical methods, you mine through data to identify opportunities for Google and our clients to operate more efficiently, from enhancing advertising efficacy to network infrastructure optimization to studying user behavior. As a Technical Lead, you do more than just crunch the numbers. You work with Engineers, Product Managers, Sales Associates and Marketing teams to adjust Google's practices according to your findings. Identifying the problem is only half the job; you also figure out the solution.\n\nWith your leadership and professional expertise, you manage a team of analysts, plan project goals and lead the overall strategy for your group. You are a recognized authority in your functional area and develop, organize and launch projects that span engineering and analysis.\nResponsibilities\nWork with large datasets and solve difficult analysis problems, applying advanced analytical methods. Conduct end-to-end analyses, including data gathering and requirements specification, processing, analysis, ongoing deliverables, and presentations.\nBuild and prototype analysis pipelines iteratively to provide insights at scale. Develop comprehensive understanding of Google data structures and metrics, advocating for changes for product development and sales activity.\nMake business recommendations with effective presentations of findings at multiple levels of stakeholders through visual displays of quantitative information.\nResearch and develop analyses and forecasting and optimization methods across ads quality, search quality, end-user behavioral modeling, and live experiments.\nManage a data science team. Interact cross-functionally with a wide variety of leaders and teams, and work closely with Engineers and Product Managers to identify opportunities for design and to assess improvements for Google products.\n\nAt Google, we don’t just accept difference—we celebrate it, we support it, and we thrive on it for the benefit of our employees, our products and our community. Google is proud to be an equal opportunity workplace and is an affirmative action employer. We are committed to equal employment opportunity regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity or Veteran status. We also consider qualified applicants regardless of criminal histories, consistent with legal requirements. See also Google's EEO Policy and EEO is the Law. If you have a disability or special need that requires accommodation, please let us know by completing this form.    3
Position Description\n\nWe are looking for a passionate, creative data scientist professional to join Inkiru Data Science team @WalmartLabs. You will have the unique opportunity to work with massive business and social data generated by Walmart Inc.'s unparalleled online and offline commerce. You will be responsible to use cutting-edge machine learning, data mining, and optimization techniques to design and prototype robust, scalable predictive models and analytics solutions. You will be a part of a cross-functional team of scientists, engineers, product managers, and business professionals that sit at the intersection of data science, big data, IT infrastructure, and business operations.\n\nResponsibilities\nPerform hands-on data exploration, processing, and analysis on massive data sets.\nUse machine learning, deep learning and data mining techniques to develop robust predictive models in areas such as Walmart Pay, Money Transfer, Bill Pay, fraud detection, anomaly detection, and product recommendation.\nPull data from data warehouse, perform feature engineering, back-test models, compare model performances and communicate the results to stakeholders.\nResearch and develop state-of-the-art algorithms that address complex business problems.\nCoach junior data scientists and supervise their day-to-day operations.\nMinimum Qualifications\nTechnical expertise in data mining, machine learning, and statistical analysis.\nProficient in machine learning and data mining packages in Python.\nExperience working with large data sets and distributed computing tools (Map/Reduce, Hadoop, Hive, or Spark).\nProgramming skills in one of the following languages: SQL, Java, or JavaScript on a UNIX or Linux platform.\nAdvanced degree (Master or PhD) in any STEM field plus 7+ years of related experience.\nAbility to work in a fast-paced, iterative development environment.\nGood communication skills, ability to work with cross functional teams of technical and non-technical members.\nAdditional Preferred Qualifications\n2+ years of people management experience.\n7+ years of risk management experience\n#LI-SN1\n\nCompany Summary\n\nWhat started small, with a single discount store and the simple idea of selling more for less, has grown over the last 50 years into the largest retailer in the world. Each week, over 260 million customers and members visit our 11,695 stores under 59 banners in 28 countries and e-commerce websites in 11 countries. With fiscal year 2017 revenue of $485.9 billion, Walmart employs approximately 2.3 million associates worldwide. Walmart continues to be a leader in sustainability, corporate philanthropy and employment opportunity. It's all part of our unwavering commitment to creating opportunities and bringing value to customers and communities around the world.\n\nPosition Summary\n\nWe are looking for a passionate, creative data scientist professional to join Inkiru Data Science team @WalmartLabs. You will have the unique opportunity to work with massive business and social data generated by Walmart Inc.'s unparalleled online and offline commerce. You will be responsible to use cutting-edge machine learning, data mining, and optimization techniques to design and prototype robust, scalable predictive models and analytics solutions. You will be a part of a cross-functional team of scientists, engineers, product managers, and business professionals that sit at the intersection of data science, big data, IT infrastructure, and business operations.\n\nResponsibilities\nPerform hands-on data exploration, processing, and analysis on massive data sets.\nUse machine learning, deep learning and data mining techniques to develop robust predictive models in areas such as Walmart Pay, Money Transfer, Bill Pay, fraud detection, anomaly detection, and product recommendation.\nPull data from data warehouse, perform feature engineering, back-test models, compare model performances and communicate the results to stakeholders.\nResearch and develop state-of-the-art algorithms that address complex business problems.\nCoach junior data scientists and supervise their day-to-day operations.                                                                                                                                   3
Data Scientist JD Digits AI Lab\n\nLocation: Mountain View, CA\n\nJob Description:\n\nJD Digits AI Lab in Mountain View, is looking for Data Scientists with strong background in analytics, statistical inference and big data. As a data scientist, you will be uniquely positioned in our team to dig deep into our big data and draw insights from it. You will translate findings into a compelling narrative about this highly strategic, fast-growing industry. Our research team has applied deep learning technologies to understand users and utilized it in various products, such as personalized feeds, product recommendation, chatbots, etc. On top of our core technologies, we are working on an intelligent user operations platform that is able to guide business decisions and maximize impact. If you're passionate about leveraging data to drive business and product decisions, we want to hear from you.\n\nResponsibilities:\n\n1) Lead the effort to communicate the state of the business to stakeholders and draw insights to make strategic decisions.\n\n2) Build core data repositories and pipelines to empower operational analysis and causal inference.\n\n3) Partner with business stakeholders to define and evaluate core business metrics.\n\n4) Team with research scientists and engineers to transform business insights into products.\n\nKey Qualifications:\nMaster (at least 5-year industrial experience) or Ph.D. (at least 2-year industrial experience) in at least one of the following fields (but not limited to): Computer Science, Statistics, Applied Mathematics, Economics, etc.\nExpert in analytical skills (SQL, SPARK, statistics, optimization, etc.).\nExperience with big data and building large-scale data pipelines end-to-end.\nExperience in working with cross-functional teams and driving data-driven decisions.\nStrong critical thinking and communication skills.\nPreferred Qualifications:\nExperience in the area of user growth and engagement.\nExperience in building big-data analytical tools and visualization tools.\nFinance/insurance industry experience is a plus but not required.\nSelf-motivated and eager to learn new things.\nTeam orientation: we work towards our goal as an agile team together, rather than individually.\nAbout JD Digits\n\nJD Digits was formerly known as JD Finance before comprehensively brand escalated in November 2018. Its operational purpose is to connect finance and real industry by using digital technology, boosting the influence of the Internet, enhancing the digital and intelligent development of industries, foster the development of the real economy and create greater social value. Centered on the cutting-edge technologies including data technology, AI, IoT and blockchain, JD Digits has completed the deployment in finance, city, agriculture, campus services and digital marketing, and integrated the personal end, corporate end and government end in terms of its clients.\n\nIn the future, JD Digits will more deeply explore current business patterns and enter into more real industry sectors.\n\nAbout JD (http://corporate.jd.com)\n\nJD.com is the largest e-commerce company in China, and the largest Chinese retailer, by revenue. The company strives to offer consumers the best online shopping experience. Through its user-friendly website, native mobile apps, and WeChat and Mobile QQ entry points, JD offers consumers a superior shopping experience. The company has the largest fulfillment infrastructure of any e-commerce company in China. As of June 30, 2017, JD.com operated 7 fulfillment centers and 335 warehouses covering 2,691 counties and districts across China, staffed by its own employees. JD.com is a member of the NASDAQ100 and a Fortune Global company.\n\nJD.com is an Equal Opportunity Employer, making decisions without regard to race, color, religion, creed, sex, sexual orientation, gender identity, marital status, national origin, age, veteran status, disability, or any other protected class.                                                                                                                                                                                                                                                                                                                   3

In [11]:
Info.DataFrame_Aggregation(df)

==============================================================================================================
Aggregation of Table
==============================================================================================================

,Name,dtypes,No of Missing,No of Uniques,Percent of Missing,First Observation,Second Observation,Third Observation,Entropy
0,Unnamed: 0,int64,0,1000,0.0,0,1,2,9.97
1,Job Title,object,0,437,0.0,Data Scientist / Machine Learning Expert,Data Scientist,Data Scientist,6.47
2,Salary Estimate,object,0,35,0.0,$96K-$101K (Glassdoor Est.),$96K-$101K (Glassdoor Est.),$96K-$101K (Glassdoor Est.),5.10
3,Job Description,object,0,898,0.0,Posting Title\nData Scientist / Machine Learni...,Overview\n\n\nData Scientist\n\nLocations US-M...,Search by Keyword\nMore Options\n\nSearch by L...,9.76
4,Rating,float64,0,32,0.0,3.9,4,4.1,4.42
5,Company Name,object,0,583,0.0,Novartis\n3.9,Analysis Group\n4.0,ABIOMED\n4.1,8.61
6,Location,object,0,85,0.0,"Cambridge, MA","Boston, MA","Danvers, MA",4.38
7,Headquarters,object,0,210,0.0,"Basel, Switzerland","Boston, MA","Danvers, MA",6.26
8,Size,object,0,9,0.0,10000+ employees,1001 to 5000 employees,1001 to 5000 employees,2.85
9,Founded,int64,0,107,0.0,1996,1981,1981,5.30
10,Type of ownership,object,0,12,0.0,Company - Public,Private Practice / Firm,Company - Public,1.77
11,Industry,object,0,66,0.0,Biotech & Pharmaceuticals,Consulting,Biotech & Pharmaceuticals,4.40
12,Sector,object,0,24,0.0,Biotech & Pharmaceuticals,Business Services,Biotech & Pharmaceuticals,3.07
13,Revenue,object,0,13,0.0,₹500+ billion (INR),₹10 to ₹50 billion (INR),₹10 to ₹50 billion (INR),2.74
14,Competitors,object,0,136,0.0,-1,-1,"Covidien, Boston Scientific",3.01

In [12]:
Info.Numeric_Count_Summary(df)

,Negative values count,Positive values count,Zero count,Unique count,Negative Infinity count,Positive Infinity count,Missing Percentage,Count of outliers
Unnamed: 0,0.0,999.0,1.0,1000.0,0.0,0.0,0.0,0.0
Rating,117.0,883.0,0.0,32.0,0.0,0.0,0.0,124.0
Founded,216.0,784.0,0.0,107.0,0.0,0.0,0.0,216.0

In [13]:
Info.Statistical_Summary(df)

,count,mean,std,min,25%,50%,75%,max,10%,90%,95%
Unnamed: 0,1000.0,499.5000,288.819436,0.0,249.75,499.5,749.25,999.0,99.9,899.1,949.050
Rating,1000.0,3.2918,1.667775,-1.0,3.30,3.8,4.20,5.0,-1.0,4.6,4.805
Founded,1000.0,1553.2820,817.329655,-1.0,1853.00,1994.0,2008.00,2019.0,-1.0,2014.0,2015.000

In [14]:
class DataFrame_Preprocessor():

    def __init__(self):
        
        print("Preprocessor object created")
        
    def Preprocessor(self,df):
        
        df['Salary Estimate'] = df['Salary Estimate'].apply(lambda x: x.split('(')[0])
        
        df['Salary Estimate'] = df['Salary Estimate'].apply(lambda x: x.replace("K","").replace("$",""))
        
        df['Min Salary'] =df['Salary Estimate'].apply(lambda x:int(x.split("-")[0]))
        
        df['Max Salary'] = df['Salary Estimate'].apply(lambda x:int(x.split("-")[1]))
        
        df['Avg Salary'] = (df['Min Salary'] + df['Max Salary'])/2
        
        df['Company Name'] = df['Company Name'].apply(lambda x: x.split("\n")[0])
        
        df['Job State'] = df['Location'].apply(lambda x: x.split(',')[1])
        
        df['Same State'] = df.apply(lambda x: 1 if x.Location == x.Headquarters else 0,axis =1)
        
        df['Age'] = df['Founded'].apply(lambda x: x if x <1 else 2020-x)
        
        df['Python'] = df['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)
        
        df['R'] = df['Job Description'].apply(lambda x: 1 if 'r studio' in x.lower() or 'r-studio' in x.lower() or ",R" in x or "R," in x or ",R" in x or " R " in x in x.lower() else 0)
        
        df['AWS'] = df['Job Description'].apply(lambda x: 1 if 'aws' in x.lower() else 0)
        
        df['Excel'] = df['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)
        
        df['Spark'] = df['Job Description'].apply(lambda x: 1 if 'spark' in x.lower() else 0)
        
        df['Tableau'] = df['Job Description'].apply(lambda x: 1 if 'tableau' in x.lower() else 0)
        
        df['SQL'] = df['Job Description'].apply(lambda x: 1 if 'sql' in x.lower() else 0)
        
        df['TensorFlow'] = df['Job Description'].apply(lambda x: 1 if 'tensorflow' in x.lower() else 0)
        
        df['PowerBI'] = df['Job Description'].apply(lambda x: 1 if 'powerbi' in x.lower() else 0)
        
        df['SaS'] = df['Job Description'].apply(lambda x: 1 if 'sas' in x.lower() else 0)
        
        df['Flask'] = df['Job Description'].apply(lambda x: 1 if 'flask' in x.lower() else 0)
        
        df['Hadoop'] = df['Job Description'].apply(lambda x: 1 if 'hadoop' in x.lower() else 0)
        
        df['Statistics']=df["Job Description"].apply(lambda x:1 if 'statistics' in x.lower() or 'statistical' in x.lower() else 0)
        
        return df

In [15]:
preprocess = DataFrame_Preprocessor()

Preprocessor object created

In [16]:
preprocess.Preprocessor(df)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Excel,Spark,Tableau,SQL,TensorFlow,PowerBI,SaS,Flask,Hadoop,Statistics
0,0,Data Scientist / Machine Learning Expert,96-101,Posting Title\nData Scientist / Machine Learni...,3.9,Novartis,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,...,0,0,0,0,0,0,0,0,0,1
1,1,Data Scientist,96-101,Overview\n\n\nData Scientist\n\nLocations US-M...,4.0,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,...,1,0,0,0,0,0,0,1,0,1
2,2,Data Scientist,96-101,Search by Keyword\nMore Options\n\nSearch by L...,4.1,ABIOMED,"Danvers, MA","Danvers, MA",1001 to 5000 employees,1981,...,1,1,0,0,1,0,0,0,1,1
3,3,Data Scientist,96-101,New England Biolabs is seeking a Data Scientis...,4.7,New England Biolabs,"Ipswich, MA","Ipswich, MA",201 to 500 employees,1974,...,1,0,0,0,0,0,0,0,0,0
4,4,Data Scientist,96-101,STR is a government research contractor specia...,4.7,Systems & Technology Research,"Woburn, MA","Woburn, MA",201 to 500 employees,2010,...,1,1,0,1,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Lead Data Scientist,87-149,Bayer is a global enterprise with core compete...,4.0,Bayer,"Whippany, NJ","Sao Paulo, Brazil",5001 to 10000 employees,1863,...,0,0,0,0,0,0,0,0,0,1
996,996,RWD Healthcare Data Scientist,87-149,"Real World Data, Healthcare Data Scientist\n\n...",3.6,W2O,"Florham Park, NJ","San Francisco, CA",201 to 500 employees,2001,...,1,0,1,1,0,0,1,0,0,1
997,997,Senior Data Scientist,87-149,"At Northwestern Mutual, we are strong, innovat...",3.8,Northwestern Mutual,"New York, NY","Milwaukee, WI",5001 to 10000 employees,1857,...,1,1,0,1,0,0,1,0,0,1
998,998,Lead Data Scientist - Private Equity,87-149,Are you a Data Scientist with some exposure to...,-1.0,Edward Daniels Group,"New York, NY","New York, NY",1 to 50 employees,2007,...,0,1,0,1,0,0,0,0,0,1
999,999,Data Scientist - OrderID,87-149,Job Description\nCompuForce is seeking an expe...,-1.0,CompuForce,"New York, NY","New York, NY",Unknown,-1,...,1,1,0,0,0,0,0,0,1,1

In [20]:
df = df.drop("Unnamed: 0",axis = 1)

In [21]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Min Salary', 'Max Salary', 'Avg Salary', 'Job State', 'Same State',
       'Age', 'Python', 'R', 'AWS', 'Excel', 'Spark', 'Tableau', 'SQL',
       'TensorFlow', 'PowerBI', 'SaS', 'Flask', 'Hadoop', 'Statistics'],
      dtype='object')

In [ ]:
df.to_csv("Scrapped_Glassdoor_Salary_cleaned.csv",index=False)